DROP TABLE IF EXISTS games;

CREATE TABLE IF NOT EXISTS games
(
    game_id VARCHAR(50),
    season REAL,
    game_type VARCHAR(50),
    week REAL,
    gameday VARCHAR(50),
    weekday VARCHAR(50),
    gametime VARCHAR(50),
    away_team VARCHAR(50),
    away_score REAL,
    home_team VARCHAR(50),
    home_score REAL,
    location VARCHAR(50),
    result REAL,
    total REAL,
    overtime REAL,
    old_game_id REAL,
    gsis REAL,
    nfl_detail_id VARCHAR(50),
    pfr VARCHAR(50),
    pff REAL,
    espn REAL,
    away_rest REAL,
    home_rest REAL,
    away_moneyline REAL,
    home_moneyline REAL,
    spread_line REAL,
    away_spread_odds REAL,
    home_spread_odds REAL,
    total_line REAL,
    under_odds REAL,
    over_odds REAL,
    div_game REAL,
    roof VARCHAR(50),
    surface VARCHAR(50),
    temp REAL,
    wind REAL,
    away_qb_id VARCHAR(50),
    home_qb_id VARCHAR(50),
    away_qb_name VARCHAR(50),
    home_qb_name VARCHAR(50),
    away_coach VARCHAR(50),
    home_coach VARCHAR(50),
    referee VARCHAR(50),
    stadium_id VARCHAR(50),
    stadium VARCHAR(50),
    games_pkey SERIAL PRIMARY KEY
);

COMMIT;